/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ApiPublicDriveCheckRouteImport } from './routes/api/public/drive-check'
import { Route as ApiPublicSendSmsRouteImport } from './routes/api/public/send-sms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDriveCheckRoute = ApiPublicDriveCheckRouteImport.update({
  id: '/api/public/drive-check',
  path: '/api/public/drive-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendSmsRoute = ApiPublicSendSmsRouteImport.update({
  id: '/api/public/send-sms',
  path: '/api/public/send-sms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public/drive-check': typeof ApiPublicDriveCheckRoute
  '/api/public/send-sms': typeof ApiPublicSendSmsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public/drive-check': typeof ApiPublicDriveCheckRoute
  '/api/public/send-sms': typeof ApiPublicSendSmsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public/drive-check': typeof ApiPublicDriveCheckRoute
  '/api/public/send-sms': typeof ApiPublicSendSmsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/api/public/drive-check' | '/api/public/send-sms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/api/public/drive-check' | '/api/public/send-sms'
  id:
    '__root__' | '/' | '/$' | '/api/public/drive-check' | '/api/public/send-sms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiPublicDriveCheckRoute: typeof ApiPublicDriveCheckRoute
  ApiPublicSendSmsRoute: typeof ApiPublicSendSmsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/drive-check': {
      id: '/api/public/drive-check'
      path: '/api/public/drive-check'
      fullPath: '/api/public/drive-check'
      preLoaderRoute: typeof ApiPublicDriveCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-sms': {
      id: '/api/public/send-sms'
      path: '/api/public/send-sms'
      fullPath: '/api/public/send-sms'
      preLoaderRoute: typeof ApiPublicSendSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiPublicDriveCheckRoute: ApiPublicDriveCheckRoute,
  ApiPublicSendSmsRoute: ApiPublicSendSmsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
